var express = require('express'),
    http    = require('http');


var app     = express(),
    port    = "2001";

http.createServer(app).listen(port, function(){
    console.log("Express API test server listening on port " + port);

    app.get("/", function(req, res){
        res.setHeader('Content-Type', 'application/json');
        res.send(" my api bookingBug server");
    });

    app.get('/services', function(req, res){
        res.setHeader('Access-Control-Allow-Origin', 'http://localhost:8000');
        res.json({


            "services":[
                {
                    "id":50524,
                    "category_id":1,
                    "name":"Seasonal Wardrobe Update",
                    "description":"What goes with what?  Which capsule pieces work for you?  We’ll break down the new season trends to create a mix and match wardrobe that works from day to night",
                    "durations":[
                        120
                    ],
                    "prices":[
                        0
                    ],
                    "detail_group_id":18529,
                    "extra":{
                        "service_type":"Personal Shopping",
                        "image_url":"https://s3-eu-west-1.amazonaws.com/bespoke.bookingbug.com/debenhams/staging/images/400_new_season_wardrobe.jpg"
                    },
                    "booking_time_step":15,
                    "is_event_group":false,
                    "type":"service",
                    "deleted":false,
                    "company_id":37000,
                    "duration_unit":"minute",
                    "min_advance_period":3600,
                    "max_advance_period":33696000,
                    "min_cancel_period":0,
                    "booking_type_public":"booking",
                    "min_bookings":1,
                    "max_bookings":1,
                    "order":0,
                    "_links":{
                        "self":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/50524"
                        },
                        "items":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/items?service_id=50524"
                        },
                        "questions":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/questions?detail_group_id=18529"
                        },
                        "days":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/day_data?service_id=50524{&month,week,date,edate,location,event_id,person_id,resource_id}",
                            "templated":true
                        },
                        "times":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/time_data?service_id=50524{&event_id,date,end_date,location,person_id,resource_id,duration,single,num_resources,group_id,resource_ids}",
                            "templated":true
                        },
                        "book":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/basket/add_item?service_id=50524{&event_id,member_id,event_chain_id,product_id,attachment_id,deal_id,package_id,bulk_purchase_id}",
                            "templated":true
                        },
                        "category":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/categories/1",
                            "title":"personalshopping"
                        },
                        "all_children":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/50524/all_children"
                        }
                    }
                },
                {
                    "id":50632,
                    "category_id":1,
                    "name":"Going on a trip?",
                    "description":"From weekend city breaks to sunshine filled days by the pool, we’ll show you how to embrace mile high style with the right bag of holiday essentials",
                    "durations":[
                        120
                    ],
                    "prices":[
                        0
                    ],
                    "detail_group_id":18530,
                    "extra":{
                        "service_type":"Personal Shopping",
                        "image_url":"https://s3-eu-west-1.amazonaws.com/bespoke.bookingbug.com/debenhams/staging/images/400_going_on_a_trip.jpg"
                    },
                    "booking_time_step":15,
                    "is_event_group":false,
                    "type":"service",
                    "deleted":false,
                    "company_id":37000,
                    "duration_unit":"minute",
                    "min_advance_period":3600,
                    "max_advance_period":33696000,
                    "min_cancel_period":0,
                    "booking_type_public":"booking",
                    "min_bookings":1,
                    "max_bookings":1,
                    "order":1,
                    "_links":{
                        "self":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/50632"
                        },
                        "items":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/items?service_id=50632"
                        },
                        "questions":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/questions?detail_group_id=18530"
                        },
                        "days":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/day_data?service_id=50632{&month,week,date,edate,location,event_id,person_id,resource_id}",
                            "templated":true
                        },
                        "times":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/time_data?service_id=50632{&event_id,date,end_date,location,person_id,resource_id,duration,single,num_resources,group_id,resource_ids}",
                            "templated":true
                        },
                        "book":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/basket/add_item?service_id=50632{&event_id,member_id,event_chain_id,product_id,attachment_id,deal_id,package_id,bulk_purchase_id}",
                            "templated":true
                        },
                        "category":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/categories/1",
                            "title":"personalshopping"
                        },
                        "all_children":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/50632/all_children"
                        }
                    }
                },
                {
                    "id":50956,
                    "category_id":1,
                    "name":"For The Bride",
                    "description":"When it comes to finding ‘that dress’ for your perfect day, our experts will give you their hand!  Book our Bridal experience to try on our exquisite selection of bridal gowns",
                    "durations":[
                        120
                    ],
                    "prices":[
                        0
                    ],
                    "detail_group_id":18533,
                    "extra":{
                        "service_type":"Personal Shopping",
                        "image_url":"https://s3-eu-west-1.amazonaws.com/bespoke.bookingbug.com/debenhams/staging/images/400_gown.jpg"
                    },
                    "booking_time_step":15,
                    "is_event_group":false,
                    "type":"service",
                    "deleted":false,
                    "company_id":37000,
                    "duration_unit":"minute",
                    "min_advance_period":3600,
                    "max_advance_period":33696000,
                    "min_cancel_period":0,
                    "booking_type_public":"booking",
                    "min_bookings":1,
                    "max_bookings":1,
                    "order":2,
                    "_links":{
                        "self":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/50956"
                        },
                        "items":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/items?service_id=50956"
                        },
                        "questions":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/questions?detail_group_id=18533"
                        },
                        "days":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/day_data?service_id=50956{&month,week,date,edate,location,event_id,person_id,resource_id}",
                            "templated":true
                        },
                        "times":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/time_data?service_id=50956{&event_id,date,end_date,location,person_id,resource_id,duration,single,num_resources,group_id,resource_ids}",
                            "templated":true
                        },
                        "book":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/basket/add_item?service_id=50956{&event_id,member_id,event_chain_id,product_id,attachment_id,deal_id,package_id,bulk_purchase_id}",
                            "templated":true
                        },
                        "category":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/categories/1",
                            "title":"personalshopping"
                        },
                        "all_children":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/50956/all_children"
                        }
                    }
                },
                {
                    "id":50740,
                    "category_id":1,
                    "name":"Special Occasions",
                    "description":"RSVP in style to every glamorous event. Our experts will ensure you make a show-stopping entrance as the belle of every ball",
                    "durations":[
                        90
                    ],
                    "prices":[
                        0
                    ],
                    "detail_group_id":18531,
                    "extra":{
                        "service_type":"Personal Shopping",
                        "image_url":"https://s3-eu-west-1.amazonaws.com/bespoke.bookingbug.com/debenhams/staging/images/400_special_occasion.jpg"
                    },
                    "booking_time_step":15,
                    "is_event_group":false,
                    "type":"service",
                    "deleted":false,
                    "company_id":37000,
                    "duration_unit":"minute",
                    "min_advance_period":3600,
                    "max_advance_period":33696000,
                    "min_cancel_period":0,
                    "booking_type_public":"booking",
                    "min_bookings":1,
                    "max_bookings":1,
                    "order":3,
                    "_links":{
                        "self":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/50740"
                        },
                        "items":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/items?service_id=50740"
                        },
                        "questions":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/questions?detail_group_id=18531"
                        },
                        "days":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/day_data?service_id=50740{&month,week,date,edate,location,event_id,person_id,resource_id}",
                            "templated":true
                        },
                        "times":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/time_data?service_id=50740{&event_id,date,end_date,location,person_id,resource_id,duration,single,num_resources,group_id,resource_ids}",
                            "templated":true
                        },
                        "book":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/basket/add_item?service_id=50740{&event_id,member_id,event_chain_id,product_id,attachment_id,deal_id,package_id,bulk_purchase_id}",
                            "templated":true
                        },
                        "category":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/categories/1",
                            "title":"personalshopping"
                        },
                        "all_children":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/50740/all_children"
                        }
                    }
                },
                {
                    "id":50848,
                    "category_id":1,
                    "name":"Mens Appointment",
                    "description":"Dressing for work, rest… or play!",
                    "durations":[
                        90
                    ],
                    "prices":[
                        0
                    ],
                    "detail_group_id":18532,
                    "extra":{
                        "service_type":"Personal Shopping",
                        "image_url":"https://s3-eu-west-1.amazonaws.com/bespoke.bookingbug.com/debenhams/staging/images/400_mens.jpg"
                    },
                    "booking_time_step":15,
                    "is_event_group":false,
                    "type":"service",
                    "deleted":false,
                    "company_id":37000,
                    "duration_unit":"minute",
                    "min_advance_period":3600,
                    "max_advance_period":33696000,
                    "min_cancel_period":0,
                    "booking_type_public":"booking",
                    "min_bookings":1,
                    "max_bookings":1,
                    "order":4,
                    "_links":{
                        "self":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/50848"
                        },
                        "items":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/items?service_id=50848"
                        },
                        "questions":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/questions?detail_group_id=18532"
                        },
                        "days":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/day_data?service_id=50848{&month,week,date,edate,location,event_id,person_id,resource_id}",
                            "templated":true
                        },
                        "times":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/time_data?service_id=50848{&event_id,date,end_date,location,person_id,resource_id,duration,single,num_resources,group_id,resource_ids}",
                            "templated":true
                        },
                        "book":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/basket/add_item?service_id=50848{&event_id,member_id,event_chain_id,product_id,attachment_id,deal_id,package_id,bulk_purchase_id}",
                            "templated":true
                        },
                        "category":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/categories/1",
                            "title":"personalshopping"
                        },
                        "all_children":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/50848/all_children"
                        }
                    }
                },
                {
                    "id":49974,
                    "category_id":1,
                    "name":"Express Appointment",
                    "description":"Looking for something extra special to complete your outfit, or short on time? We’ll show you how to take one simple look – and make a stylish statement",
                    "durations":[
                        45
                    ],
                    "prices":[
                        0
                    ],
                    "detail_group_id":18535,
                    "extra":{
                        "service_type":"Personal Shopping",
                        "image_url":"https://s3-eu-west-1.amazonaws.com/bespoke.bookingbug.com/debenhams/staging/images/400_express_appointment.jpg"
                    },
                    "booking_time_step":15,
                    "is_event_group":false,
                    "type":"service",
                    "deleted":false,
                    "company_id":37000,
                    "duration_unit":"minute",
                    "min_advance_period":3600,
                    "max_advance_period":33696000,
                    "min_cancel_period":0,
                    "booking_type_public":"booking",
                    "min_bookings":1,
                    "max_bookings":1,
                    "order":5,
                    "_links":{
                        "self":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/49974"
                        },
                        "items":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/items?service_id=49974"
                        },
                        "questions":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/questions?detail_group_id=18535"
                        },
                        "days":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/day_data?service_id=49974{&month,week,date,edate,location,event_id,person_id,resource_id}",
                            "templated":true
                        },
                        "times":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/time_data?service_id=49974{&event_id,date,end_date,location,person_id,resource_id,duration,single,num_resources,group_id,resource_ids}",
                            "templated":true
                        },
                        "book":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/basket/add_item?service_id=49974{&event_id,member_id,event_chain_id,product_id,attachment_id,deal_id,package_id,bulk_purchase_id}",
                            "templated":true
                        },
                        "category":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/categories/1",
                            "title":"personalshopping"
                        },
                        "all_children":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/49974/all_children"
                        }
                    }
                },
                {
                    "id":52216,
                    "category_id":5,
                    "name":"Group Booking - 2 people",
                    "description":"From creating capsule wardrobes to finding show stopping outfits for a special occasion, you and your friends can share a Personal Shopping experience together, in the comfort of a private suite",
                    "durations":[
                        120
                    ],
                    "prices":[
                        0
                    ],
                    "detail_group_id":18633,
                    "extra":{
                        "service_type":"Group Booking",
                        "image_url":"https://s3-eu-west-1.amazonaws.com/bespoke.bookingbug.com/debenhams/staging/images/400_group.jpg"
                    },
                    "booking_time_step":15,
                    "is_event_group":false,
                    "type":"service",
                    "deleted":false,
                    "company_id":37000,
                    "duration_unit":"minute",
                    "min_advance_period":3600,
                    "max_advance_period":33696000,
                    "min_cancel_period":86400,
                    "booking_type_public":"booking",
                    "min_bookings":1,
                    "max_bookings":1,
                    "order":6,
                    "_links":{
                        "self":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/52216"
                        },
                        "items":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/items?service_id=52216"
                        },
                        "questions":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/questions?detail_group_id=18633"
                        },
                        "days":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/day_data?service_id=52216{&month,week,date,edate,location,event_id,person_id,resource_id}",
                            "templated":true
                        },
                        "times":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/time_data?service_id=52216{&event_id,date,end_date,location,person_id,resource_id,duration,single,num_resources,group_id,resource_ids}",
                            "templated":true
                        },
                        "book":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/basket/add_item?service_id=52216{&event_id,member_id,event_chain_id,product_id,attachment_id,deal_id,package_id,bulk_purchase_id}",
                            "templated":true
                        },
                        "category":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/categories/5",
                            "title":"Everything Else"
                        },
                        "all_children":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/52216/all_children"
                        }
                    }
                },
                {
                    "id":51172,
                    "category_id":5,
                    "name":"Group Booking - 3 people",
                    "description":"From creating capsule wardrobes to finding show stopping outfits for a special occasion, you and your friends can share a Personal Shopping experience together, in the comfort of a private suite",
                    "durations":[
                        180
                    ],
                    "prices":[
                        0
                    ],
                    "detail_group_id":18633,
                    "extra":{
                        "service_type":"Group Booking",
                        "image_url":"https://s3-eu-west-1.amazonaws.com/bespoke.bookingbug.com/debenhams/staging/images/400_group.jpg"
                    },
                    "booking_time_step":15,
                    "is_event_group":false,
                    "type":"service",
                    "deleted":false,
                    "company_id":37000,
                    "duration_unit":"minute",
                    "min_advance_period":3600,
                    "max_advance_period":33696000,
                    "min_cancel_period":0,
                    "booking_type_public":"booking",
                    "min_bookings":1,
                    "max_bookings":1,
                    "order":7,
                    "_links":{
                        "self":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/51172"
                        },
                        "items":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/items?service_id=51172"
                        },
                        "questions":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/questions?detail_group_id=18633"
                        },
                        "days":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/day_data?service_id=51172{&month,week,date,edate,location,event_id,person_id,resource_id}",
                            "templated":true
                        },
                        "times":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/time_data?service_id=51172{&event_id,date,end_date,location,person_id,resource_id,duration,single,num_resources,group_id,resource_ids}",
                            "templated":true
                        },
                        "book":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/basket/add_item?service_id=51172{&event_id,member_id,event_chain_id,product_id,attachment_id,deal_id,package_id,bulk_purchase_id}",
                            "templated":true
                        },
                        "category":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/categories/5",
                            "title":"Everything Else"
                        },
                        "all_children":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/51172/all_children"
                        }
                    }
                },
                {
                    "id":51280,
                    "category_id":5,
                    "name":"Group Booking - 4 people",
                    "description":"From creating capsule wardrobes to finding show stopping outfits for a special occasion, you and your friends can share a Personal Shopping experience together, in the comfort of a private suite",
                    "durations":[
                        180
                    ],
                    "prices":[
                        0
                    ],
                    "detail_group_id":18633,
                    "extra":{
                        "service_type":"Group Booking",
                        "image_url":"https://s3-eu-west-1.amazonaws.com/bespoke.bookingbug.com/debenhams/staging/images/400_group.jpg"
                    },
                    "booking_time_step":60,
                    "is_event_group":false,
                    "type":"service",
                    "deleted":false,
                    "company_id":37000,
                    "duration_unit":"minute",
                    "min_advance_period":3600,
                    "max_advance_period":33696000,
                    "min_cancel_period":0,
                    "booking_type_public":"booking",
                    "min_bookings":1,
                    "max_bookings":1,
                    "order":8,
                    "_links":{
                        "self":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/51280"
                        },
                        "items":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/items?service_id=51280"
                        },
                        "questions":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/questions?detail_group_id=18633"
                        },
                        "days":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/day_data?service_id=51280{&month,week,date,edate,location,event_id,person_id,resource_id}",
                            "templated":true
                        },
                        "times":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/time_data?service_id=51280{&event_id,date,end_date,location,person_id,resource_id,duration,single,num_resources,group_id,resource_ids}",
                            "templated":true
                        },
                        "book":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/basket/add_item?service_id=51280{&event_id,member_id,event_chain_id,product_id,attachment_id,deal_id,package_id,bulk_purchase_id}",
                            "templated":true
                        },
                        "category":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/categories/5",
                            "title":"Everything Else"
                        },
                        "all_children":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/51280/all_children"
                        }
                    }
                },
                {
                    "id":51388,
                    "category_id":5,
                    "name":"Group Booking - 5 people",
                    "description":"From creating capsule wardrobes to finding show stopping outfits for a special occasion, you and your friends can share a Personal Shopping experience together, in the comfort of a private suite",
                    "durations":[
                        180
                    ],
                    "prices":[
                        0
                    ],
                    "detail_group_id":18633,
                    "extra":{
                        "service_type":"Group Booking",
                        "image_url":"https://s3-eu-west-1.amazonaws.com/bespoke.bookingbug.com/debenhams/staging/images/400_group.jpg"
                    },
                    "booking_time_step":15,
                    "is_event_group":false,
                    "type":"service",
                    "deleted":false,
                    "company_id":37000,
                    "duration_unit":"minute",
                    "min_advance_period":3600,
                    "max_advance_period":33696000,
                    "min_cancel_period":0,
                    "booking_type_public":"booking",
                    "min_bookings":1,
                    "max_bookings":1,
                    "order":9,
                    "_links":{
                        "self":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/51388"
                        },
                        "items":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/items?service_id=51388"
                        },
                        "questions":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/questions?detail_group_id=18633"
                        },
                        "days":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/day_data?service_id=51388{&month,week,date,edate,location,event_id,person_id,resource_id}",
                            "templated":true
                        },
                        "times":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/time_data?service_id=51388{&event_id,date,end_date,location,person_id,resource_id,duration,single,num_resources,group_id,resource_ids}",
                            "templated":true
                        },
                        "book":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/basket/add_item?service_id=51388{&event_id,member_id,event_chain_id,product_id,attachment_id,deal_id,package_id,bulk_purchase_id}",
                            "templated":true
                        },
                        "category":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/categories/5",
                            "title":"Everything Else"
                        },
                        "all_children":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/51388/all_children"
                        }
                    }
                },
                {
                    "id":51496,
                    "category_id":5,
                    "name":"Group Booking - 6 people",
                    "description":"From creating capsule wardrobes to finding show stopping outfits for a special occasion, you and your friends can share a Personal Shopping experience together, in the comfort of a private suite",
                    "durations":[
                        180
                    ],
                    "prices":[
                        0
                    ],
                    "detail_group_id":18633,
                    "extra":{
                        "service_type":"Group Booking",
                        "image_url":"https://s3-eu-west-1.amazonaws.com/bespoke.bookingbug.com/debenhams/staging/images/400_group.jpg"
                    },
                    "booking_time_step":15,
                    "is_event_group":false,
                    "type":"service",
                    "deleted":false,
                    "company_id":37000,
                    "duration_unit":"minute",
                    "min_advance_period":3600,
                    "max_advance_period":33696000,
                    "min_cancel_period":0,
                    "booking_type_public":"booking",
                    "min_bookings":1,
                    "max_bookings":1,
                    "order":10,
                    "_links":{
                        "self":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/51496"
                        },
                        "items":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/items?service_id=51496"
                        },
                        "questions":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/questions?detail_group_id=18633"
                        },
                        "days":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/day_data?service_id=51496{&month,week,date,edate,location,event_id,person_id,resource_id}",
                            "templated":true
                        },
                        "times":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/time_data?service_id=51496{&event_id,date,end_date,location,person_id,resource_id,duration,single,num_resources,group_id,resource_ids}",
                            "templated":true
                        },
                        "book":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/basket/add_item?service_id=51496{&event_id,member_id,event_chain_id,product_id,attachment_id,deal_id,package_id,bulk_purchase_id}",
                            "templated":true
                        },
                        "category":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/categories/5",
                            "title":"Everything Else"
                        },
                        "all_children":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/51496/all_children"
                        }
                    }
                },
                {
                    "id":51604,
                    "category_id":6,
                    "name":"Bridesmaids - 2 people",
                    "description":"Let our experts help you select beautiful bridesmaid dresses to compliment your own.\r\n",
                    "durations":[
                        90
                    ],
                    "prices":[
                        0
                    ],
                    "detail_group_id":18534,
                    "extra":{
                        "service_type":"Group Booking",
                        "image_url":"https://s3-eu-west-1.amazonaws.com/bespoke.bookingbug.com/debenhams/staging/images/400_bridesmaids.jpg"
                    },
                    "booking_time_step":15,
                    "is_event_group":false,
                    "type":"service",
                    "deleted":false,
                    "company_id":37000,
                    "duration_unit":"minute",
                    "min_advance_period":0,
                    "max_advance_period":33696000,
                    "min_cancel_period":0,
                    "booking_type_public":"booking",
                    "min_bookings":1,
                    "max_bookings":1,
                    "order":11,
                    "_links":{
                        "self":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/51604"
                        },
                        "items":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/items?service_id=51604"
                        },
                        "questions":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/questions?detail_group_id=18534"
                        },
                        "days":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/day_data?service_id=51604{&month,week,date,edate,location,event_id,person_id,resource_id}",
                            "templated":true
                        },
                        "times":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/time_data?service_id=51604{&event_id,date,end_date,location,person_id,resource_id,duration,single,num_resources,group_id,resource_ids}",
                            "templated":true
                        },
                        "book":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/basket/add_item?service_id=51604{&event_id,member_id,event_chain_id,product_id,attachment_id,deal_id,package_id,bulk_purchase_id}",
                            "templated":true
                        },
                        "category":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/categories/6",
                            "title":"Bridesmaids"
                        },
                        "all_children":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/51604/all_children"
                        }
                    }
                },
                {
                    "id":51712,
                    "category_id":6,
                    "name":"Bridesmaids - 3 people",
                    "description":"Let our experts help you select beautiful bridesmaid dresses to compliment your own.",
                    "durations":[
                        120
                    ],
                    "prices":[
                        0
                    ],
                    "detail_group_id":18534,
                    "extra":{
                        "service_type":"Group Booking",
                        "image_url":"https://s3-eu-west-1.amazonaws.com/bespoke.bookingbug.com/debenhams/staging/images/400_bridesmaids.jpg"
                    },
                    "booking_time_step":15,
                    "is_event_group":false,
                    "type":"service",
                    "deleted":false,
                    "company_id":37000,
                    "duration_unit":"minute",
                    "min_advance_period":0,
                    "max_advance_period":33696000,
                    "min_cancel_period":0,
                    "booking_type_public":"booking",
                    "min_bookings":1,
                    "max_bookings":1,
                    "order":12,
                    "_links":{
                        "self":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/51712"
                        },
                        "items":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/items?service_id=51712"
                        },
                        "questions":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/questions?detail_group_id=18534"
                        },
                        "days":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/day_data?service_id=51712{&month,week,date,edate,location,event_id,person_id,resource_id}",
                            "templated":true
                        },
                        "times":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/time_data?service_id=51712{&event_id,date,end_date,location,person_id,resource_id,duration,single,num_resources,group_id,resource_ids}",
                            "templated":true
                        },
                        "book":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/basket/add_item?service_id=51712{&event_id,member_id,event_chain_id,product_id,attachment_id,deal_id,package_id,bulk_purchase_id}",
                            "templated":true
                        },
                        "category":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/categories/6",
                            "title":"Bridesmaids"
                        },
                        "all_children":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/51712/all_children"
                        }
                    }
                },
                {
                    "id":51820,
                    "category_id":6,
                    "name":"Bridesmaids - 4 people",
                    "description":"Let our experts help you select beautiful bridesmaid dresses to compliment your own.",
                    "durations":[
                        120
                    ],
                    "prices":[
                        0
                    ],
                    "detail_group_id":18534,
                    "extra":{
                        "service_type":"Group Booking",
                        "image_url":"https://s3-eu-west-1.amazonaws.com/bespoke.bookingbug.com/debenhams/staging/images/400_bridesmaids.jpg"
                    },
                    "booking_time_step":15,
                    "is_event_group":false,
                    "type":"service",
                    "deleted":false,
                    "company_id":37000,
                    "duration_unit":"minute",
                    "min_advance_period":0,
                    "max_advance_period":33696000,
                    "min_cancel_period":0,
                    "booking_type_public":"booking",
                    "min_bookings":1,
                    "max_bookings":1,
                    "order":13,
                    "_links":{
                        "self":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/51820"
                        },
                        "items":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/items?service_id=51820"
                        },
                        "questions":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/questions?detail_group_id=18534"
                        },
                        "days":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/day_data?service_id=51820{&month,week,date,edate,location,event_id,person_id,resource_id}",
                            "templated":true
                        },
                        "times":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/time_data?service_id=51820{&event_id,date,end_date,location,person_id,resource_id,duration,single,num_resources,group_id,resource_ids}",
                            "templated":true
                        },
                        "book":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/basket/add_item?service_id=51820{&event_id,member_id,event_chain_id,product_id,attachment_id,deal_id,package_id,bulk_purchase_id}",
                            "templated":true
                        },
                        "category":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/categories/6",
                            "title":"Bridesmaids"
                        },
                        "all_children":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/51820/all_children"
                        }
                    }
                },
                {
                    "id":51928,
                    "category_id":6,
                    "name":"Bridesmaids - 5 people",
                    "description":"Let our experts help you select beautiful bridesmaid dresses to compliment your own.",
                    "durations":[
                        120
                    ],
                    "prices":[
                        0
                    ],
                    "detail_group_id":18534,
                    "extra":{
                        "service_type":"Group Booking",
                        "image_url":"https://s3-eu-west-1.amazonaws.com/bespoke.bookingbug.com/debenhams/staging/images/400_bridesmaids.jpg"
                    },
                    "booking_time_step":15,
                    "is_event_group":false,
                    "type":"service",
                    "deleted":false,
                    "company_id":37000,
                    "duration_unit":"minute",
                    "min_advance_period":0,
                    "max_advance_period":33696000,
                    "min_cancel_period":0,
                    "booking_type_public":"booking",
                    "min_bookings":1,
                    "max_bookings":1,
                    "order":14,
                    "_links":{
                        "self":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/51928"
                        },
                        "items":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/items?service_id=51928"
                        },
                        "questions":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/questions?detail_group_id=18534"
                        },
                        "days":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/day_data?service_id=51928{&month,week,date,edate,location,event_id,person_id,resource_id}",
                            "templated":true
                        },
                        "times":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/time_data?service_id=51928{&event_id,date,end_date,location,person_id,resource_id,duration,single,num_resources,group_id,resource_ids}",
                            "templated":true
                        },
                        "book":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/basket/add_item?service_id=51928{&event_id,member_id,event_chain_id,product_id,attachment_id,deal_id,package_id,bulk_purchase_id}",
                            "templated":true
                        },
                        "category":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/categories/6",
                            "title":"Bridesmaids"
                        },
                        "all_children":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/51928/all_children"
                        }
                    }
                },
                {
                    "id":52036,
                    "category_id":6,
                    "name":"Bridesmaids - 6 people",
                    "description":"Let our experts help you select beautiful bridesmaid dresses to compliment your own.",
                    "durations":[
                        120
                    ],
                    "prices":[
                        0
                    ],
                    "detail_group_id":18534,
                    "extra":{
                        "service_type":"Group Booking",
                        "image_url":"https://s3-eu-west-1.amazonaws.com/bespoke.bookingbug.com/debenhams/staging/images/400_bridesmaids.jpg"
                    },
                    "booking_time_step":15,
                    "is_event_group":false,
                    "type":"service",
                    "deleted":false,
                    "company_id":37000,
                    "duration_unit":"minute",
                    "min_advance_period":0,
                    "max_advance_period":33696000,
                    "min_cancel_period":0,
                    "booking_type_public":"booking",
                    "min_bookings":1,
                    "max_bookings":1,
                    "order":15,
                    "_links":{
                        "self":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/52036"
                        },
                        "items":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/items?service_id=52036"
                        },
                        "questions":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/questions?detail_group_id=18534"
                        },
                        "days":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/day_data?service_id=52036{&month,week,date,edate,location,event_id,person_id,resource_id}",
                            "templated":true
                        },
                        "times":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/time_data?service_id=52036{&event_id,date,end_date,location,person_id,resource_id,duration,single,num_resources,group_id,resource_ids}",
                            "templated":true
                        },
                        "book":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/basket/add_item?service_id=52036{&event_id,member_id,event_chain_id,product_id,attachment_id,deal_id,package_id,bulk_purchase_id}",
                            "templated":true
                        },
                        "category":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/categories/6",
                            "title":"Bridesmaids"
                        },
                        "all_children":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/52036/all_children"
                        }
                    }
                },
                {
                    "id":50092,
                    "category_id":2,
                    "name":"Gift shopping - 1 to 3 people",
                    "durations":[
                        45
                    ],
                    "prices":[
                        0
                    ],
                    "detail_group_id":18536,
                    "extra":{
                        "service_type":"Gift Shopping",
                        "image_url":"http://images.bookingbug.com/debenhams/gifts.jpg"
                    },
                    "booking_time_step":45,
                    "is_event_group":false,
                    "type":"service",
                    "deleted":false,
                    "company_id":37000,
                    "duration_unit":"minute",
                    "min_advance_period":0,
                    "max_advance_period":5184000,
                    "min_cancel_period":86400,
                    "booking_type_public":"booking",
                    "min_bookings":1,
                    "max_bookings":1,
                    "order":16,
                    "_links":{
                        "self":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/50092"
                        },
                        "items":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/items?service_id=50092"
                        },
                        "questions":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/questions?detail_group_id=18536"
                        },
                        "days":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/day_data?service_id=50092{&month,week,date,edate,location,event_id,person_id,resource_id}",
                            "templated":true
                        },
                        "times":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/time_data?service_id=50092{&event_id,date,end_date,location,person_id,resource_id,duration,single,num_resources,group_id,resource_ids}",
                            "templated":true
                        },
                        "book":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/basket/add_item?service_id=50092{&event_id,member_id,event_chain_id,product_id,attachment_id,deal_id,package_id,bulk_purchase_id}",
                            "templated":true
                        },
                        "category":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/categories/2",
                            "title":"giftshopping"
                        },
                        "all_children":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/50092/all_children"
                        }
                    }
                },
                {
                    "id":50416,
                    "category_id":2,
                    "name":"Gift shopping - 4 or more people",
                    "durations":[
                        60
                    ],
                    "prices":[
                        0
                    ],
                    "detail_group_id":18536,
                    "extra":{
                        "service_type":"Gift Shopping",
                        "image_url":"http://images.bookingbug.com/debenhams/gifts.jpg"
                    },
                    "booking_time_step":60,
                    "is_event_group":false,
                    "type":"service",
                    "deleted":false,
                    "company_id":37000,
                    "duration_unit":"minute",
                    "min_advance_period":0,
                    "max_advance_period":5184000,
                    "min_cancel_period":86400,
                    "booking_type_public":"booking",
                    "min_bookings":1,
                    "max_bookings":1,
                    "order":17,
                    "_links":{
                        "self":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/50416"
                        },
                        "items":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/items?service_id=50416"
                        },
                        "questions":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/questions?detail_group_id=18536"
                        },
                        "days":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/day_data?service_id=50416{&month,week,date,edate,location,event_id,person_id,resource_id}",
                            "templated":true
                        },
                        "times":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/time_data?service_id=50416{&event_id,date,end_date,location,person_id,resource_id,duration,single,num_resources,group_id,resource_ids}",
                            "templated":true
                        },
                        "book":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/basket/add_item?service_id=50416{&event_id,member_id,event_chain_id,product_id,attachment_id,deal_id,package_id,bulk_purchase_id}",
                            "templated":true
                        },
                        "category":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/categories/2",
                            "title":"giftshopping"
                        },
                        "all_children":{
                            "href":"https://debenhams-staging.bookingbug.com/api/v1/37000/services/50416/all_children"
                        }
                    }
                }
            ]
          });

        })
 })

